name: "Test PR Trigger"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Test workflow trigger
        run: |
          echo "✅ Workflow triggered successfully!"
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR Number: ${{ github.event.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "PR Base SHA: ${{ github.event.pull_request.base.sha }}"
